---
- name: Install and start the Nginx
  hosts: localhost
  become: yes

  tasks:
  - name: Installing nginx
    apt:
      name: nginx
      state: present

  - name: Starting nginx service
    service:
      name: nginx
      state: started
      enabled: true

